[package]
name = "tests_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "api_actix"
path = "src/api_actix.rs"

[dependencies]
actix = "0.13.0"
